name: gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 16 ]

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - uses: actions/checkout@master
      - run: yarn install
      - run: yarn build
        env:
          NITRO_PRESET: service-worker
          NITRO_APP_ROUTER_BASE: /nitro-deploys/
      - uses: JamesIves/github-pages-deploy-action@4.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: '.output/public'
          CLEAN: true
